---
- hosts: server 
  gather_facts: true
  gather_subset: min
  become: yes

  tasks:
    - import_tasks: tasks/base.yml
    - import_tasks: tasks/python.yml 
      #    - import_tasks: tasks/systemd.example.yml
    - import_tasks: tasks/net-tools.yml
