---
#
#
# base packages
#
#
    - name: modify terminal info (needed for kitty, alacritty, others)
      shell: echo 'export TERM=xterm-256color' >> /home/vagrant/.bash_profile
    - name: install base packages 
      dnf: 
        name:
          - vim-enhanced 
          - tree 
          - git
          - curl
          - wget
        state: latest 
